### ISSUE TITLE
Test with PHP 7.4

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#819] opened 2019-10-30 12:42 UTC
We probably need to disable the platform requirements constrains for Composer for this.

**Comment by opengeek** [comment] 2019-12-03 02:56
Is this going to get done soon? This issue is blocking the `composer install` of ALL projects which depend on this package for no good reason that I can see. The problem is resolved by merely changing the PHP platform requirements to use `>=5.6` instead of specifying each version. Is there any way this could be fast-tracked into the current major releases?

**Comment by oliverklee** [comment] 2019-12-03 10:12
@opengeek We could do a feature release 3.1.0 for this. Would you be willing to create a pull request for adding 7.4 support and adding 7.4 to Travis CI?

**Comment by burzum** [comment] 2019-12-05 10:19
@oliverklee when can we expect a release for this?

**Comment by oliverklee** [comment] 2019-12-05 11:11
Probably sometime next week depending on when I can put the time into this.
If you want to help to speed things up (which I would greatly appreciate): #821 needs a condition in the `.travis.yml` to only execute Psalm on PHP  < 7.4.

**Comment by burzum** [comment] 2019-12-05 13:49
@oliverklee OK, but the issue doesn't seem to be Psalm but something with phpunit? https://travis-ci.org/MyIntervals/emogrifier/jobs/620305033?utm_medium=notification&utm_source=github_status

**Comment by oliverklee** [comment] 2019-12-05 14:02
@burzum It's like this:

- We currently are using PHPUnit 6.5 and Psalm 3.2 to be able to run the tests on PHP 7.0 as well (which is the lowest PHP version Emogrifier currently supports).
- Psalm 3.2 has bugs that prevent it from running under PHP 7.4
- Psalm 3.7 requires PHP >= 7.1, and is also has dependencies that prevent if from being installed alongside with PHPUnit 6.5
- In addition, Psalm 3.7 has different rules than Psalm 3.2, which would require changes to our codebase (which I'd like to avoid for a short-term release to support PHP 7.4).

So the idea is to skip the Psalm checks on Travis CI on PHP >= 7.4. And when we raise our minimum version requirement for PHP to 7.1, we can update PHPUnit and Psalm and also update our code for the latest Psalm.

**Comment by oliverklee** [comment] 2019-12-05 14:03
(And I would not be comfortable declaring compatibility with unbounded PHP >= 7.0 version requirement without having our tests run on the respective PHP versions.)

**Comment by burzum** [comment] 2019-12-05 14:05
I've tried to reproduce what I see on travis locally but it just works for me without the issues I see on travis. This is what it runs, no?

```sh
composer remove --dev vimeo/psalm
composer update --prefer-lowest
```

**Comment by oliverklee** [comment] 2019-12-05 14:05
To avoid these kinds of dependency problems in the long run, we should not require the CI tools as Composer dev dependencies, but have them as PHARs using Phive the way https://github.com/sebastianbergmann/phpunit/ does it.

**Comment by oliverklee** [comment] 2019-12-05 14:06
@burzum Yes, and also `composer ci:psalm` is executed (which is where the problem occurs).

**Comment by burzum** [comment] 2019-12-05 14:19
@oliverklee OK, I'll give it a try, no promise but I'll try it. I have a surgery day today and see what I can get done after that or tomorrow, depending on whats going on at work.

**Comment by burzum** [comment] 2019-12-05 19:37
@oliverklee how do you want to do the setup with Phive? Add the files in their according version to each branch / version? Or set it up when running Travis? I'm working on getting Phive set up only on Travis right now.

**Comment by oliverklee** [comment] 2019-12-05 22:07
@burzum As this issue is about getting support for PHP 7.4, I've moved your comment to the ticket #822 that is about using Phive.

**Closed** 2019-12-26 16:35 UTC
Labels: enhancement
