### ISSUE TITLE
Emogrifier is removing closing curly braces from handlbars proprties in CSS

### ISSUE THREAD

**Issue by badalsurana** [MyIntervals/emogrifier#1060] opened 2021-05-17 19:07 UTC
I have handlebars properties in my css. Below is the example
`<style>
 p {
    color: {{options.color}};
}
</style>`

emogrifier is returning `<p style="color:{{options.color">text</p>`

notice the closing curly braces are not present and this is breaking my templates. Is there any way to fix this?

**Comment by JakeQZ** [comment] 2021-05-17 23:10
Hi @badalsurana,

Emogrifier does not currently support these kinds of substitutions in the CSS, and only supports native CSS.

However, there may be a couple of workarounds.

If it is possible to invoke the Handlebars template expansion before invoking Emogrifier, this would solve the problem, as Emogrifier would then be working with the final CSS, rather than a template.

Alternatively (if that is not possible or desirable), it may be possible to substitute the `{{` and `}}` with something else before invoking Emogrifier, then substitute them back after.

As you are seeing, the first `}` is being treated as the end of the rule (this may also impact the parsing of subsequent rules).  The `{` and `}` characters are specific tokens in CSS, demarking selectors from declarations, or statments within nested at-rules.

`:` and `;` also have significance within CSS property declarations, but for the most part other characters which appear to be part of a property value are passed on verbatim.  I have not tested this, but you might try substituting `{{` and `}}` with `[[` and `]]` before invoking Emogrifier, then performing the reverse substitution after.

**Comment by badalsurana** [comment] 2021-05-18 06:35
Hi @JakeQZ Thank you for your quick reply.

Is it possible to add support for escaping the curly braces in CSS? something like `\{\{options.color\}\}`

**Comment by JakeQZ** [comment] 2021-05-18 16:54
> Is it possible to add support for escaping the curly braces in CSS? something like `\{\{options.color\}\}`

That could in theory work.  However, we are planning to use a third party library (probably [Sabberworm /
PHP-CSS-Parser](https://github.com/sabberworm/PHP-CSS-Parser) for CSS parsing), probably from the next major release.  From then, any support for Handlebars properties would depend on such support being present in that library.

A quick test shows that it does not support Handlebars properties either, although it would preserve a property value in quotes (e.g. `color: "{{options.color}}";`.  However, you would then need to remove the quotes from the resultant HTML (template), since, e.g. `color: "green";` is not valid (it must be `color: green;`).

(Note that Emogrifier does not currently have any special handling of property values in quotes and would still treat `}` as the end of the declarations block even if in quotes.)

**Comment by oliverklee** [comment] 2021-05-22 17:23
Closing this ticket then as this is not a bug in Emogrifier.

@badalsurana If you find any other (possible) bug, please feel free to report more tickets! This is very much appreciated. :heart:

**Closed by oliverklee** 2021-05-22 17:23 UTC
