### ISSUE TITLE
Warning: DOMXPath::query(): Invalid expression in pelago/emogrifier/Classes/Emogrifier.php

### ISSUE THREAD

**Issue by graeme-norman** [MyIntervals/emogrifier#350] opened 2016-09-28 16:37 UTC
I have a generated CSS file for an email template which is including some partial sass files from my main app - the css is being generated fine but is giving me alot of the following warning...

Warning: DOMXPath::query(): Invalid expression in /var/**/**/**/vendor/pelago/emogrifier/Classes/Emogrifier.php 

Here is the CSS output which seems to be causing the error - http://pastebin.com/re6VKSsc  

Any idea what part of it could be the problem as I can't seem to narrow it down!! 

Thanks

**Comment by oliverklee** [comment] 2016-09-29 06:13
Hi @graeme-norman, thanks for the bug report!

This probably either is a bug in the CSS parser or a missing feature.

This is how you can help narrow this down:
-  also put some HTML that you use (or that also triggers the problem)
-  try to reduce the CSS to the minimum that still triggers the problem

Thanks again!

**Comment by graeme-norman** [comment] 2016-09-29 09:52
Hi @oliverklee, thanks for getting back to me. 

I tried removing parts of the template and even swapping the whole template for a single div with Hello world and it was still outputting the same warnings... 

So we managed to set the warning error handler and logged $cssRule['selector'] (line 369 of Emogrifier.php) for each time it got the warning and here is the resulting list of the offending selectors

Here is the log file output. Hope that helps - http://pastebin.com/D6MfdjrQ

Thanks

**Comment by oliverklee** [comment] 2016-09-29 11:12
Thanks for the log! With which version of Emogrifier does this happen? Does the problem also occur with the latest Git master?

**Comment by oliverklee** [comment] 2016-09-29 11:33
(We recently released Emogrifier 1.1.0. This version added quite a lot of supported selectors over 1.0.0.)

**Comment by graeme-norman** [comment] 2016-09-29 11:43
That's ok. We are using the latest 1.1.0 - I checked for the update yesterday when we found the issue but unfortunately didn't fix the warnings.

**Comment by oliverklee** [comment] 2016-09-29 13:01
Thanks! I'll have a look at it. (It might take a while, though.)

**Comment by graeme-norman** [comment] 2016-09-30 15:32
Ok great, thanks!

**Comment by montchr** [comment] 2016-10-20 17:26
I'm also getting this issue with Emogrifier 1.1.0 and PHP 7.0.11.

**Comment by montchr** [comment] 2016-10-20 18:42
As an example of CSS that triggers the warning (from Normalize.css):

```css
button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button; /* 2 */
  cursor: pointer; /* 3 */
}
```

Seems it's connected to attribute selectors?

**Comment by dereuromark** [comment] 2016-10-24 15:29
Can one silence it for now?

**Comment by Bigwebmaster** [comment] 2016-11-09 01:23
I am also getting this same error with an email template view that I am passing through to emogrifier. I narrowed down the cause to the error to this exact CSS rule:

        div[style*="margin: 16px 0"] {
            margin:0 !important;
        }

When I take that rule out, everything works with no errors. Hope that helps to solve this issue.

**Comment by oliverklee** [comment] 2016-11-09 09:32
Hi @Bigwebmaster, thanks for the additional information! I've just created issue #352 for exactly this problem. Please let's continue the discussion there.

**Comment by sammuell** [comment] 2017-03-08 17:49
I ran into the same issue today, also with normalize.css. The problem is not a colon character. 
I made a (failing) test case here: https://github.com/sammuell/emogrifier/commit/01376ae740ba8e599da746ba2c8802e64a1794b7

**Comment by oliverklee** [comment] 2017-03-09 15:00
Thanks! Adding a link to the PR now: #375

**Comment by Khaleel** [comment] 2017-11-10 12:56
Was this fixed?

**Comment by oliverklee** [comment] 2017-11-10 13:08
No, this is not fixed yet. Only the error should now be silently ignored in non-debug mode.

**Comment by oliverklee** [comment] 2018-01-07 11:33
Closing this ticket as it mixed too many different issues. Please feel free to create new tickets for problem with specific HTML/Css.

**Closed by oliverklee** 2018-01-07 11:33 UTC
Labels: bug
