### ISSUE TITLE
Drop support for Symfony 4.4

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1198] opened 2022-11-28 18:20 UTC
As of today (2022-11-18), [Symfony 4.4 has reached its end of life](https://github.com/symfony/symfony/releases/tag/v4.4.49).

**Comment by JakeQZ** [comment] 2023-12-06 02:05
Effectively a duplicate of #1242, which supersedes this and has more commentary.  Closing.

**Closed by JakeQZ** 2023-12-06 02:05 UTC
Labels: duplicate, dependencies
