### ISSUE TITLE
Minified CSS is not parsing correctly

### ISSUE THREAD

**Issue by coughsyrupgit** [MyIntervals/emogrifier#370] opened 2017-02-28 08:25 UTC
If the css is minified, parsing is not going pretty well.

Here's an example.
We've got minified one-line css file with code:

`.order-totals {background: #e0edf6;}.order-totals>tr>th{font-weight: normal;}.order-totals>tr>th,.order-totals>tr>td{padding: 10px;text-align: right;}.order-totals+tr th,.order-totals+tr td{padding-top: 0;}.price{white-space: nowrap;}`

And the next html:
```
...
<tfoot class="order-totals">
    <tr>
        <th>
            Some th text
        </th>
        <td>
            Some td text
        </td>
        <td class="price">
            Any price
        </td>
    </tr>    
</tfoot>
...
```

In this case, after emogrifier the HTML will be next:
```
<tfoot class="order-totals" style="background: #e0edf6;">
    <tr>
        <th>
            Some th text
        </th>
        <td>
            Some td text
        </td>
        <td class="price">
            Any price
        </td>
    </tr>
</tfoot>
```

This is because of the spaces absence. If we add some spaces and modify the css above to:

`.order-totals {background: #e0edf6;} .order-totals > tr > th{font-weight: normal;} .order-totals > tr > th,.order-totals > tr > td{padding: 10px;text-align: right;}.order-totals + tr th,.order-totals + tr td{padding-top: 0;} .price{white-space: nowrap;}`

We will get the correct result: 
```
<tfoot class="order-totals" style="background: #e0edf6;">
     <tr>
         <th style="font-weight:normal;padding:10px;text-align:right;">
            Some th text
        </th>
        <td style="padding: 10px;text-align: right;">
            Some td text
        </td>
        <td class="price" style="white-space:nowrap;padding:10px;text-align:right;">
            Any price
        </td>
    </tr>
</tfoot>
```

I think, that would be wonderful if Emogrifier could deal with minified css, because it used widely. For example, Magento 2 uses the Emogrifier for styling emails, and everything looked good until the minify css is on. It was such a disappointment to see the emails styles broken.

**Comment by oliverklee** [comment] 2017-02-28 11:38
Hi @coughsyrupgit, thanks for the detailed bug report!

Would you be willing to reduce this to a minimal test case?

And a PR with unit tests and a fix would be even more awesome!

**Comment by coughsyrupgit** [comment] 2017-03-01 15:57
Hi @oliverklee.
I would love to, but I am not quite familiar with tests writing =/
If I can help in some another way (maybe providing more specific details), I would do it with pleasure.

**Comment by coughsyrupgit** [comment] 2017-03-01 16:27
I'm a frontender, so please guide me, if I do something wrong...
I've run `composer install` and have gotten `Nothing to install`, so I guess, everything is okay with dependencies. 
I'm using Magento 2, so I guess the tests are running in a bit different way here -> [Magento Docs](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-test.html). Should I use this guide to run the tests?

**Comment by oliverklee** [comment] 2017-03-02 12:29
Okay, I think we need to start one step earlier in the process. :-)

Have you already forked the Emogrifier project, and cloned the fork to your local machine? Then, if you run ```composer install``` from the directory of the cloned fork, composer should install phpunit and PHP_CodeSniffer. 

(Also please have a look at the CONTRIBUTING.md file. It should have a few helpful links.)

Please let me know how the forking and cloning works out for you.

**Comment by chedaroo** [comment] 2017-04-20 12:27
@oliverklee I had a quick look to see if I could fix this but struggled to figure out where you match css selectors.

Looking at your tests, [selectorDataProvider()](https://github.com/jjriv/emogrifier/blob/master/Tests/Unit/EmogrifierTest.php#L539) appears to check for the equivilent selectors of:
```scss
p > span {[...]} // Line 559
p >span {[...]} // Line 661
p> span {[...]} // Line 663
```
But not:
```scss
p>span {[...]} // missing valid css variation (no space)
```
I guess `p>span` would be the minimal test case requested above?

Apologies for not being able to assist further.

**Comment by oliverklee** [comment] 2017-04-21 16:10
Hi @chedaroo, I've just added this edge case to the tests. It still is green: https://travis-ci.org/jjriv/emogrifier/builds/224392618

So this is not a minimal test case (in the sense that it still exhibits the bug).

**Comment by mmenozzi** [comment] 2018-02-02 12:50
Hi @oliverklee,
What's the status of this issue?
Magento has upgraded to version 1.2.0 of this library and the issue seems gone (https://github.com/magento/magento2/commit/ae0af893a3e39a4a98c12136dddad92de3eef93b) but the issue here is still open. Moreover you added this issue to the 1.3.0 milestone but the version 2.0.0 is already out. So what's the status? Is now minified CSS handled correctly? And if so since what version?
Thank you very much for your work anyway.

**Comment by oliverklee** [comment] 2018-02-02 13:12
Hi @mmenozzi, according to @chedaroo, there still is a problem. However, we currently don't have a test case that is failing. @mmenozzi If you can create a failing test case (or verify that the problem is gone), that would be very helpful so we can either close this issue or know which exact cases to fix. Thanks!

(Generally, "minified CSS" is not something that either works or that doesn't in Emogrifier. Minification changes the CSS in many ways which could create different edge cases.)

**Comment by oliverklee** [comment] 2018-02-02 15:38
Okay, closing this for now. @mmenozzi, @chedaroo, @coughsyrupgit, please feel free to open a new ticket with a particular line of CSS that does not parse yet. Thanks!

**Closed by oliverklee** 2018-02-02 15:38 UTC
Labels: bug, waiting for feedback

**Comment by mmenozzi** [comment] 2018-02-05 07:49
Hi @oliverklee,
thank you for your update.
I think that the particular problem with Magento's minification was fixed with this PR https://github.com/MyIntervals/emogrifier/pull/322.
So it's ok for me closing this issue and opening a new ticket when a particular CSS doesn't parse correctly.
