### ISSUE TITLE
Invalid Expression

### ISSUE THREAD

**Issue by electricBonfire** [MyIntervals/emogrifier#559] opened 2018-04-04 17:26 UTC
I am getting the following error:

Invalid expression in selector >> [option-label="White"] 

I am using v1.2.0

**Comment by oliverklee** [comment] 2018-04-04 17:28
Hi @electricBonfire, thanks for the bug report. Which version of Emogrifier are you using?

And are you using Emogrifier in debug mode or non-debug mode?

And could you please post the minimal HTML and CSS required to reproduce the problem? Thanks!

**Comment by electricBonfire** [comment] 2018-04-04 17:29
I am using Magento2, I'm not sure how emogrifier is incorporated but I am in developer mode.

**Comment by oliverklee** [comment] 2018-04-04 17:30
Could you please test whether the problem is resolved if you update the Emogrifier dependency in `composer.json` to `"^2.0.0"` and then run `composer update pelago/emogrifier`?

**Comment by electricBonfire** [comment] 2018-04-04 17:35
That seemed to do the trick! The base Magento 2 deps had v0.1.1. I had bumped this up to 1.2.0.
Thanks for the quick reply, I haven't had much luck with responses to anything in the magento community

**Comment by oliverklee** [comment] 2018-04-04 17:37
@electricBonfire That's good to hear! Then I'm closing this ticket now. If you encounter any other bug in the latest Emogrifier version (2.0.0), please feel free to open another ticket.

**Closed by oliverklee** 2018-04-04 17:37 UTC
Labels: bug
