### ISSUE TITLE
Fatal error: Uncaught RuntimeException: DOMXPath::query():

### ISSUE THREAD

**Issue by nikmauro** [MyIntervals/emogrifier#439] opened 2017-12-15 11:58 UTC
Fatal error: Uncaught RuntimeException: DOMXPath::query(): Invalid expression in /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 1108 in /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php:1785 Stack trace: #0 [internal function]: Pelago\Emogrifier->handleXpathQueryWarnings(2, 'DOMXPath::query...', '/var/www/vhosts...', 1108, Array) #1 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(1108): DOMXPath->query('//*[contains(co...') #2 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(1063): Pelago\Emogrifier->existsMatchForCssSelector(Object(DOMXPath), '.mobile_link a[...') #3 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(412): Pelago\Emogrifier->copyCssWithMediaToStyleNode(Object(DOMDocument), Object(DOMXPath), '@media screen a...') #4 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(328): Pelago\Em in /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 1785

```CSS

a[href^="tel"], a[href^="sms"] {
                text-decoration: none;
                color: black; /* or whatever your want */
                pointer-events: none;
                cursor: default;
            }

            .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
                text-decoration: default;
                color: orange !important; /* or whatever your want */
                pointer-events: auto;
                cursor: default;
            }

 @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
            a[href^="tel"], a[href^="sms"] {
                text-decoration: none;
                color: blue; /* or whatever your want */
                pointer-events: none;
                cursor: default;
            }
```

**Comment by oliverklee** [comment] 2017-12-16 09:27
Hi @nikmauro, thanks for the bug report!

Both problems (the missing support for the attribute selector with ^ and the exception for unrecognized CSS in non-debug mode) should be already fixed in the current master. Could you please test whether the problem still occurs if you are using the current version from GitHub? Thanks!

**Comment by zoliszabo** [comment] 2017-12-16 09:38
As far as I can see in the stack trace, @nikmauro is already using the most current version.

I will also check later what the problem may be.

**Comment by oliverklee** [comment] 2017-12-16 09:54
@zoliszabo Thanks!

**Comment by nikmauro** [comment] 2017-12-18 12:55
Here my version from composer     "pelago/emogrifier": "dev-master / 1.3.x-dev" and the debug mode is private $debug = false;

**Comment by zoliszabo** [comment] 2017-12-27 19:13
@nikmauro : While I can't reproduce the exception with the CSS you have provided (I am quite sure that the CSS that caused the exception was slightly different), you did point out some problems. After some deep investigation I split them into two distinct issues:
#441 (for which I already did a PR: #442)
#443

**Comment by oliverklee** [comment] 2018-01-07 11:22
Closing, as this now is handled in the two other issues.

**Comment by oliverklee** [comment] 2018-01-07 11:22
@nikmauro Please feel free to add tickets for any other problems you encounter.

**Closed by oliverklee** 2018-01-07 11:22 UTC
Labels: bug
